version: "3"                                        
services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - ./filebrowser/filebrowser.json:/.filebrowser.json
      - ./filebrowser/database.db:/database.db
      - ./data:/srv
    ports:
      - 8080:80
